name: test

on:
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      # From: https://github.com/KittKode/headless-electron/blob/master/Dockerfile
      # - name: Dependencies to run Electron in Github Actions
      #   if: matrix.platform == 'ubuntu-latest'
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libgtk2.0-0 libgconf-2-4 libasound2 libxtst6 libxss1 libnss3 xvfb

      - name: Build YAML
        if: matrix.platform != 'ubuntu-latest'
        run: |
          npm i -g yarn
          yarn
          yarn test:make-input
      
      - name: Run tests
        run: |
          yarn test

      - name: Upload to release
        if: matrix.platform != 'ubuntu-latest'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: menu.yml
          asset_name: menu-${{ runner.os }}.yml
          tag: release-${{ github.ref }}
          overwrite: true
          body: menu-template
